### ISSUE TITLE
Create chat > UI issues in the create chat screen

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#1034] opened 2021-10-26 03:34 UTC
# Precondition
Design: https://app.zeplin.io/project/5fd7afb0317dc8827d6a8fb5/screen/61427342c0083152958857d6

# Actual Result and Expected Result
![image](https://user-images.githubusercontent.com/69950655/138802443-6643ec18-0ab9-45f3-9710-ed6a836f9188.png)
1. The icon of "New chat" is incorrect
=> Should update as in the design

2. The label `New Channel / New Chat/ Direct Chats` is displayed with the light font on iOS
=> It should display with the MEDIUM font on iOS

3. The member name is displayed with the bold font on both OS
=> It should display with the REGULAR font

# Environment
Build version: 1.0.1
Device:
Samsung Galaxy J7 - Android 8.1.0 - 5.5 inch
iPhone 11 Promax - iOS 14.4 - 6.46 inch
QA environment

**Comment by sherlockvn** [comment] 2022-03-30 08:56
# The problem is already fixed in Android
![image](https://user-images.githubusercontent.com/43041967/160769914-bf51264b-d06f-45b6-832c-e56e11a9a044.png)

Build version: 1.0.7
Device:
- Google Pixel 4 - Android 11.0 x86 - 5.7 inch
QA environment

**Closed** 2023-01-30 15:26 UTC
Labels: bug, Minor, UI, mobile
