### ISSUE TITLE
User feedback > Request new feature" Mark channel as read/unread"

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#567] opened 2021-05-11 07:18 UTC
The mobile app should have feature "Mark channel as read/unread" as on the Web version

![Peek 2021-05-11 14-17](https://user-images.githubusercontent.com/69950655/117774446-b5691000-b263-11eb-8182-a1877605ca47.gif)

Please confirm with our PO/BA if we should have this on app

**Comment by tlle14** [comment] 2021-05-11 07:19
@PokoinikRWS Hi, please confirm this feature.

**Comment by tlle14** [comment] 2021-07-23 11:18
@bobs4462 it seems our customers cannot wait to use this feature. Please take a look!

**Comment by bobs4462** [comment] 2021-08-18 12:43
duplicate of #450

**Closed by bobs4462** 2021-08-18 12:43 UTC
Labels: improvement, Feedback
