### ISSUE TITLE
Message jump animation

### ISSUE THREAD

**Issue by BenoitTallandier** [linagora/Twake-Mobile#1347] opened 2022-04-19 07:16 UTC
Today, when we open a channel, we have to open it on the last message. But when we search for a specific message, for example, I need to open the channel with the good scroll (message searched in the middle of the screen).

We need a feature like 
`jumpToMessage(messageId)` that would open the channel with the message targeted in the middle of the screen. Here an example to understand more.

https://user-images.githubusercontent.com/22451567/166896626-6a06dda4-7c85-44fd-b3c2-159a23be21af.mov

Web task : https://github.com/linagora/Twake/issues/1925

**Comment by RomaricMourgues** [comment] 2022-04-19 07:22
Duplicate of #1925

**Comment by BenoitTallandier** [comment] 2022-04-19 07:23
It's the mobile tas[](url)

**Comment by RomaricMourgues** [comment] 2022-04-19 07:45
Oh sorry !

**Closed** 2022-07-13 07:58 UTC
Labels: mobile
