### ISSUE TITLE
Displaying a gray screen when a new user logged in 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake-Mobile#648] opened 2021-06-28 09:14 UTC
# Precondition
A new user has not been invited to any workspace yet or be deactivated

# Actual Result
When the new user logged in to the app, the app displays a gray screen without any information.
https://user-images.githubusercontent.com/69950655/123611021-5c613580-d82b-11eb-90df-1f3bb957177e.mp4

# Expected Result
There should have a message to inform the user about his state.

# Environment
Build version: 3.0.0
Device: Xiaomi Redmi Note 9 - Android 10 - 6.53 inch

**Comment by bobs4462** [comment] 2021-06-30 14:29
Should be fixed in the next build

**Comment by tlle14** [comment] 2021-07-06 09:13
Hi @bobs4462 

1. What happens when a deactivated user login to the app? It seems he still be able to be added in a workspace/ channel or login successfully or using the app as usual. 


2. About the whole new user, it displays the sync data screen and tells the new user that the sync is failed, he needs to try again and never succeed. I think this behavior is inappropriate. 
- It shouldn't display the sync data screen for the user who hasn't  invited to any workspace yet (nothing to sync)
- The app should inform to the user he hasn't been invited to any workspace yet in the current Company. It's better if we guide him on what to do. 

https://images.zenhubusercontent.com/309637937/55fda1c8-432d-4e9e-a5a5-7b78073374c5/rpreplay_final1625562326.mp4

**Comment by bobs4462** [comment] 2021-07-06 09:21
@BenoitTallandier is it possible to have a user in a complete limbo? Without any company/workspace?

**Comment by BenoitTallandier** [comment] 2021-07-06 09:47
Yes, it can happen. For example, you were invited in Twake by a colleague. After, you are removed, then you have any company. So, you should have a screen saying that you have to create your company or wait for invitation. I can build a US for that if you want :)

**Comment by tlle14** [comment] 2021-07-06 10:24
Here is the story from Twake Console, it may help: https://ci.linagora.com/linagora/lgs/saas/portal/specifications/issues/30

**Comment by bobs4462** [comment] 2021-07-06 12:11
> Yes, it can happen. For example, you were invited in Twake by a colleague. After, you are removed, then you have any company. So, you should have a screen saying that you have to create your company or wait for invitation. I can build a US for that if you want :) 

Yes, please do, also some technical details, of how to figure out orphaned user would be of great help

**Comment by bobs4462** [comment] 2021-07-23 14:13
@BastiaanVanGaalen can you provide us with design of screen to show the user if he was deleted and/kicked out from all the companies?

**Comment by BastiaanVanGaalen** [comment] 2021-09-03 11:52
@bobs4462 https://zpl.io/VQ4W6r4

**Comment by BenoitTallandier** [comment] 2021-09-06 10:20
@BastiaanVanGaalen 
Are you sure about this message "Something went wrong" ?
The user is just waiting for invitation or creation. It is not a bug, it is just a special state for the user.  :)

**Comment by BastiaanVanGaalen** [comment] 2021-09-07 21:14
@BenoitTallandier Suggest the wording, please. The case is unusual, indeed, so special working is expected.

**Comment by BenoitTallandier** [comment] 2021-09-09 08:34
On the desktop version, we have that :

![image](https://user-images.githubusercontent.com/22451567/132651918-df3573f7-ce88-414b-b1ca-586efc7a2122.png)


We can improve the wording with "It looks like no one has invited you yet. Wait for invitation or create your own company".

**Comment by BastiaanVanGaalen** [comment] 2021-09-15 18:58
@BenoitTallandier @bobs4462 @EvGen94 https://zpl.io/Vq4nM6Y done

**Comment by bobs4462** [comment] 2021-09-24 13:10
@tlle14 you can close this one, the progress will be tracked here #980

**Closed** 2021-09-24 14:14 UTC
Labels: bug, Medium
